### ISSUE TITLE
Starting rsync with pre-built static binary doesn't work (on ESXi8)

### ISSUE THREAD

**Issue by Kahz3l** [itiligent/RSYNC-for-ESXi#1]
Hi,
just downloading and chmod 755 with the static binary doesn't work. 

The following is happening:
```
[root@esxi01:/vmfs/volumes/65797aed-ef2b98e0-53d1-002324c71b97/bin] ll
total 6272
drwxr-xr-x    1 root     root         73728 Dec 28 23:21 .
drwxr-xr-t    1 root     root         73728 Dec 28 23:21 ..
-rwxr-xr-x    1 root     root       4194592 Dec 28 22:20 rsync
[root@esxi01:/vmfs/volumes/65797aed-ef2b98e0-53d1-002324c71b97/bin] /vmfs/volumes/65797aed-ef2b98e0-53d1-0
02324c71b97/bin/rsync --version
-sh: /vmfs/volumes/65797aed-ef2b98e0-53d1-002324c71b97/bin/rsync: Operation not permitted
```

**Comment by Kahz3l** [comment]
Esxi version 8.0U2

**Comment by Kahz3l** [comment]
Issue solved, it's a new enforced security feature starting in esxi 8.0.
To deactivate:
esxcli system settings advanced set -o /User/execInstalledOnly -i 0
https://docs.vmware.com/en/VMware-vSphere/8.0/vsphere-security/GUID-DF6A7974-62F9-47DB-A990-963F3B3AEA77.html

**Comment by itiligent** [comment]
Thanks for sharing this.
This project was originally bult for ESXi7 and works well, but I have not tested with ESXi8, so this is helpful info.


________________________________
